blank_issues_enabled: false
contact_links:
  - name: âœ‹ I have a question or need support
    url: https://discord.wizarr.org
    about: We use GitHub for tracking bugs, please check out our Discord channel for freaky fast support.
  - name: ðŸŒŸ Feature request
    url: https://github.com/wizarrrrr/wizarr/discussions/new?category=feature-request
    about: Please use our GitHub Discussion for making feature requests.
  - name: ðŸ«£ I'm unsure where to go
    url: https://discord.wizarr.org
    about: If you are unsure where to go, then joining our Discord is recommended; Just ask!
